name: freelancehub
services:
- name: web
  source_dir: /frontend
  github:
    repo: Itwoss/freelancehub
    branch: main
  run_command: npm start
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  envs:
  - key: NODE_ENV
    value: production
  - key: MONGODB_URI
    value: ${db.MONGODB_URI}
  - key: DATABASE_URL
    value: ${db.DATABASE_URL}
  - key: NEXTAUTH_URL
    value: https://urchin-app-olxze.ondigitalocean.app
  - key: NEXTAUTH_SECRET
    value: ${NEXTAUTH_SECRET}
  - key: NEXT_PUBLIC_RAZORPAY_KEY_ID
    value: rzp_live_RPjP2rRnGLu4yD
  - key: RAZORPAY_KEY_SECRET
    value: ddorF1ExMdUIXbWwDsxvhwkV
  - key: RAZORPAY_ENVIRONMENT
    value: production
  - key: NEXT_PUBLIC_BASE_URL
    value: https://urchin-app-olxze.ondigitalocean.app
  build_command: npm run build:mongodb
  http_port: 3000
